// src/components/Input/Input.tsx
import React from 'react';
import './Input.css';

export interface InputProps {
  /** Input label */
  label?: string;
  /** Input placeholder */
  placeholder?: string;
  /** Input type */
  type?: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url';
  /** Input value */
  value?: string;
  /** Input state */
  state?: 'default' | 'error' | 'success' | 'disabled';
  /** Helper text displayed below the input */
  helperText?: string;
  /** Error message displayed below the input (shown when state is error) */
  errorMessage?: string;
  /** Show leading icon */
  iconLeft?: React.ReactNode;
  /** Show trailing icon */
  iconRight?: React.ReactNode;
  /** Mark the field as optional (displays "(optional)" next to label) */
  optional?: boolean;
  /** Change handler */
  onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void;
  /** Optional additional className */
  className?: string;
}

export const Input: React.FC<InputProps> = ({
  label,
  placeholder,
  type = 'text',
  value,
  state = 'default',
  helperText,
  errorMessage,
  iconLeft,
  iconRight,
  optional = false,
  onChange,
  className = '',
}) => {
  const baseClass = 'sparkline-input';
  const wrapperClasses = [
    `${baseClass}-wrapper`,
    className,
  ].filter(Boolean).join(' ');

  const inputClasses = [
    baseClass,
    `${baseClass}--${state}`,
    iconLeft ? `${baseClass}--with-icon-left` : '',
    iconRight ? `${baseClass}--with-icon-right` : '',
  ].filter(Boolean).join(' ');

  const disabled = state === 'disabled';
  const showError = state === 'error' && errorMessage;
  const showHelper = helperText && !showError;

  return (
    <div className={wrapperClasses} data-component="input">
      {label && (
        <div className={`${baseClass}__label-row`}>
          <label className={`${baseClass}__label`}>
            {label}
          </label>
          {optional && <span className={`${baseClass}__optional`}>(optional)</span>}
        </div>
      )}
      <div className={`${baseClass}__input-wrapper ${baseClass}__input-wrapper--${state}`}>
        {iconLeft && (
          <span className={`${baseClass}__icon ${baseClass}__icon--left`}>
            {iconLeft}
          </span>
        )}
        <input
          type={type}
          className={inputClasses}
          placeholder={placeholder}
          value={value}
          onChange={onChange}
          disabled={disabled}
        />
        {iconRight && (
          <span className={`${baseClass}__icon ${baseClass}__icon--right`}>
            {iconRight}
          </span>
        )}
      </div>
      {showError && (
        <div className={`${baseClass}__message-row`}>
          <span className={`${baseClass}__message ${baseClass}__message--error`}>
            {errorMessage}
          </span>
        </div>
      )}
      {showHelper && (
        <div className={`${baseClass}__message-row`}>
          <span className={`${baseClass}__message ${baseClass}__message--helper`}>
            {helperText}
          </span>
        </div>
      )}
    </div>
  );
};

// src/components/Input/Input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sparkline-input',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './Input.component.html',
  styleUrls: ['./Input.css'],
})
export class InputComponent {
  @Input() label?: string;
  @Input() placeholder?: string;
  @Input() type: 'text' | 'email' | 'password' | 'number' | 'tel' | 'url' = 'text';
  @Input() value?: string;
  @Input() state: 'default' | 'error' | 'success' | 'disabled' = 'default';
  @Input() helperText?: string;
  @Input() errorMessage?: string;
  @Input() showIconLeft = false;
  @Input() showIconRight = false;
  @Input() optional = false;
  @Output() valueChange = new EventEmitter<string>();

  get isDisabled(): boolean {
    return this.state === 'disabled';
  }

  get showError(): boolean {
    return this.state === 'error' && !!this.errorMessage;
  }

  get showHelper(): boolean {
    return !!this.helperText && !this.showError;
  }

  get inputClasses(): string {
    const base = 'sparkline-input';
    return [
      base,
      `${base}--${this.state}`,
      this.showIconLeft ? `${base}--with-icon-left` : '',
      this.showIconRight ? `${base}--with-icon-right` : '',
    ].filter(Boolean).join(' ');
  }

  onInput(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.valueChange.emit(input.value);
  }
}

<div class="sparkline-input-wrapper" data-component="input">
  <div *ngIf="label" class="sparkline-input__label-row">
    <label class="sparkline-input__label">{{ label }}</label>
    <span *ngIf="optional" class="sparkline-input__optional">(optional)</span>
  </div>
  <div class="sparkline-input__input-wrapper sparkline-input__input-wrapper--{{ state }}">
    <span *ngIf="showIconLeft" class="sparkline-input__icon sparkline-input__icon--left">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
    <input
      [type]="type"
      [class]="inputClasses"
      [placeholder]="placeholder || ''"
      [value]="value || ''"
      [disabled]="isDisabled"
      (input)="onInput($event)"
    />
    <span *ngIf="showIconRight" class="sparkline-input__icon sparkline-input__icon--right">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
  </div>
  <div *ngIf="showError" class="sparkline-input__message-row">
    <span class="sparkline-input__message sparkline-input__message--error">{{ errorMessage }}</span>
  </div>
  <div *ngIf="showHelper" class="sparkline-input__message-row">
    <span class="sparkline-input__message sparkline-input__message--helper">{{ helperText }}</span>
  </div>
</div>
