// src/components/Button/Button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sparkline-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './Button.component.html',
  styleUrls: ['./Button.css'],
})
export class ButtonComponent {
  @Input() label = 'Button';
  @Input() size: 'small' | 'medium' | 'large' = 'large';
  @Input() variant: 'filled' | 'outlined' | 'text' = 'filled';
  @Input() disabled = false;
  @Input() showLeftIcon = false;
  @Input() showRightIcon = false;
  @Output() clicked = new EventEmitter<void>();

  get classes(): string {
    const base = 'sparkline-button';
    return [
      base,
      `${base}--${this.size}`,
      `${base}--${this.variant}`,
      this.disabled ? `${base}--disabled` : '',
    ].filter(Boolean).join(' ');
  }

  onClick(): void {
    if (!this.disabled) {
      this.clicked.emit();
    }
  }
}

<button
  type="button"
  [class]="classes"
  [disabled]="disabled"
  (click)="onClick()"
  data-component="button"
>
  <span *ngIf="showLeftIcon" class="sparkline-button__icon sparkline-button__icon--left">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M15 18L9 12L15 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </span>
  <span class="sparkline-button__label">{{ label }}</span>
  <span *ngIf="showRightIcon" class="sparkline-button__icon sparkline-button__icon--right">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M9 18L15 12L9 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </span>
</button>

// src/components/Button/Button.tsx
import React from 'react';
import './Button.css';

export interface ButtonProps {
  /**
   * Button label text
   */
  label: string;
  /**
   * Button size variant
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Button type/style variant
   */
  variant?: 'filled' | 'outlined' | 'text';
  /**
   * Disabled state
   */
  disabled?: boolean;
  /**
   * Show left icon
   */
  showLeftIcon?: boolean;
  /**
   * Show right icon
   */
  showRightIcon?: boolean;
  /**
   * Custom left icon component
   */
  iconLeft?: React.ReactNode;
  /**
   * Custom right icon component
   */
  iconRight?: React.ReactNode;
  /**
   * Optional click handler
   */
  onClick?: () => void;
  /**
   * Optional additional className
   */
  className?: string;
}

/**
 * Primary UI component for user interaction
 */
export const Button: React.FC<ButtonProps> = ({
  label,
  size = 'large',
  variant = 'filled',
  disabled = false,
  showLeftIcon = false,
  showRightIcon = false,
  iconLeft,
  iconRight,
  onClick,
  className = '',
}) => {
  const baseClass = 'sparkline-button';
  const classes = [
    baseClass,
    `${baseClass}--${size}`,
    `${baseClass}--${variant}`,
    disabled && `${baseClass}--disabled`,
    className,
  ].filter(Boolean).join(' ');

  return (
    <button
      type="button"
      className={classes}
      onClick={onClick}
      disabled={disabled}
      data-component="button"
    >
      {showLeftIcon && (
        <span className={`${baseClass}__icon ${baseClass}__icon--left`}>
          {iconLeft || (
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15 18L9 12L15 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </span>
      )}
      <span className={`${baseClass}__label`}>{label}</span>
      {showRightIcon && (
        <span className={`${baseClass}__icon ${baseClass}__icon--right`}>
          {iconRight || (
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M9 18L15 12L9 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </span>
      )}
    </button>
  );
};
