// src/app/components/button/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

export type ButtonType = 'filled' | 'outlined' | 'text';
export type ButtonSize = 'large' | 'small';
export type ButtonState = 'default' | 'hover' | 'pressed' | 'focus' | 'disabled';

@Component({
  selector: 'sp-button',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
  host: {
    '[class]': 'hostClasses',
    '[class.sp-button--disabled]': "state === 'disabled'",
    '(mouseenter)': 'onMouseEnter()',
    '(mouseleave)': 'onMouseLeave()',
    '(mousedown)': 'onMouseDown()',
    '(mouseup)': 'onMouseUp()',
    '(focus)': 'onFocus()',
    '(blur)': 'onBlur()',
    '(click)': 'onClick($event)',
    '[attr.tabindex]': "state === 'disabled' ? -1 : 0",
    'role': 'button',
    '[attr.aria-disabled]': "state === 'disabled'",
  },
})
export class ButtonComponent {
  @Input() label = 'Button';
  @Input() type: ButtonType = 'filled';
  @Input() size: ButtonSize = 'large';
  @Input() state: ButtonState = 'default';
  @Input() showLeftIcon = false;
  @Input() showRightIcon = false;
  @Input() showText = true;

  @Output() buttonClick = new EventEmitter<MouseEvent>();

  private _interactiveState: 'hover' | 'pressed' | 'focus' | null = null;

  get hostClasses(): string {
    return [
      'sp-button',
      `sp-button--${this.type}`,
      `sp-button--${this.size}`,
      `sp-button--${this.activeState}`,
    ].join(' ');
  }

  get activeState(): ButtonState {
    if (this.state === 'disabled') return 'disabled';
    if (this._interactiveState === 'pressed') return 'pressed';
    if (this._interactiveState === 'focus') return 'focus';
    if (this._interactiveState === 'hover') return 'hover';
    return this.state;
  }

  onMouseEnter(): void {
    if (this.state !== 'disabled') this._interactiveState = 'hover';
  }

  onMouseLeave(): void {
    if (this._interactiveState !== 'focus') this._interactiveState = null;
  }

  onMouseDown(): void {
    if (this.state !== 'disabled') this._interactiveState = 'pressed';
  }

  onMouseUp(): void {
    if (this.state !== 'disabled') this._interactiveState = 'hover';
  }

  onFocus(): void {
    if (this.state !== 'disabled') this._interactiveState = 'focus';
  }

  onBlur(): void {
    this._interactiveState = null;
  }

  onClick(event: MouseEvent): void {
    if (this.state !== 'disabled') {
      this.buttonClick.emit(event);
    }
  }
}

<ng-container *ngIf="showLeftIcon">
  <span class="sp-button__icon sp-button__icon--left">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M19 12H5M5 12L12 19M5 12L12 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </span>
</ng-container>

<span *ngIf="showText" class="sp-button__label">{{ label }}</span>

<ng-container *ngIf="showRightIcon">
  <span class="sp-button__icon sp-button__icon--right">
    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M5 12H19M19 12L12 5M19 12L12 19" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
  </span>
</ng-container>

// src/components/Button/Button.tsx
import React from 'react';
import './Button.css';

export interface ButtonProps {
  /**
   * Button label text
   */
  label: string;
  /**
   * Button size variant
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Button type/style variant
   */
  variant?: 'filled' | 'outlined' | 'text';
  /**
   * Disabled state
   */
  disabled?: boolean;
  /**
   * Show left icon
   */
  showLeftIcon?: boolean;
  /**
   * Show right icon
   */
  showRightIcon?: boolean;
  /**
   * Custom left icon component
   */
  iconLeft?: React.ReactNode;
  /**
   * Custom right icon component
   */
  iconRight?: React.ReactNode;
  /**
   * Optional click handler
   */
  onClick?: () => void;
  /**
   * Optional additional className
   */
  className?: string;
}

/**
 * Primary UI component for user interaction
 */
export const Button: React.FC<ButtonProps> = ({
  label,
  size = 'large',
  variant = 'filled',
  disabled = false,
  showLeftIcon = false,
  showRightIcon = false,
  iconLeft,
  iconRight,
  onClick,
  className = '',
}) => {
  const baseClass = 'sparkline-button';
  const classes = [
    baseClass,
    `${baseClass}--${size}`,
    `${baseClass}--${variant}`,
    disabled && `${baseClass}--disabled`,
    className,
  ].filter(Boolean).join(' ');

  return (
    <button
      type="button"
      className={classes}
      onClick={onClick}
      disabled={disabled}
      data-component="button"
    >
      {showLeftIcon && (
        <span className={`${baseClass}__icon ${baseClass}__icon--left`}>
          {iconLeft || (
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15 18L9 12L15 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </span>
      )}
      <span className={`${baseClass}__label`}>{label}</span>
      {showRightIcon && (
        <span className={`${baseClass}__icon ${baseClass}__icon--right`}>
          {iconRight || (
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M9 18L15 12L9 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          )}
        </span>
      )}
    </button>
  );
};
