// src/components/Switch/Switch.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sparkline-switch',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './Switch.component.html',
  styleUrls: ['./Switch.css'],
})
export class SwitchComponent {
  @Input() label?: string;
  @Input() checked = false;
  @Input() disabled = false;
  @Input() size: 'small' | 'medium' | 'large' = 'medium';
  @Output() checkedChange = new EventEmitter<boolean>();

  get classes(): string {
    const base = 'sparkline-switch';
    return [
      base,
      `${base}--${this.size}`,
      this.disabled ? `${base}--disabled` : '',
    ].filter(Boolean).join(' ');
  }

  onChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.checkedChange.emit(input.checked);
  }
}

<label [class]="classes" data-component="switch">
  <input
    type="checkbox"
    class="sparkline-switch__input"
    [checked]="checked"
    [disabled]="disabled"
    (change)="onChange($event)"
  />
  <span class="sparkline-switch__slider">
    <span class="sparkline-switch__thumb"></span>
  </span>
  <span *ngIf="label" class="sparkline-switch__label">{{ label }}</span>
</label>

// src/components/Switch/Switch.tsx
import React from 'react';
import './Switch.css';

export interface SwitchProps {
  /**
   * Switch label
   */
  label?: string;
  /**
   * Checked state
   */
  checked?: boolean;
  /**
   * Disabled state
   */
  disabled?: boolean;
  /**
   * Switch size
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Change handler
   */
  onChange?: (checked: boolean) => void;
  /**
   * Optional additional className
   */
  className?: string;
}

export const Switch: React.FC<SwitchProps> = ({
  label,
  checked = false,
  disabled = false,
  size = 'medium',
  onChange,
  className = '',
}) => {
  const baseClass = 'sparkline-switch';

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (onChange) {
      onChange(e.target.checked);
    }
  };

  return (
    <label
      className={`${baseClass} ${baseClass}--${size} ${disabled ? `${baseClass}--disabled` : ''} ${className}`}
      data-component="switch"
    >
      <input
        type="checkbox"
        className={`${baseClass}__input`}
        checked={checked}
        disabled={disabled}
        onChange={handleChange}
      />
      <span className={`${baseClass}__slider`}>
        <span className={`${baseClass}__thumb`} />
      </span>
      {label && <span className={`${baseClass}__label`}>{label}</span>}
    </label>
  );
};
