// src/components/Card/Card.tsx
import React from 'react';
import './Card.css';

export interface CardProps {
  /**
   * Card title
   */
  title?: string;
  /**
   * Card content
   */
  children: React.ReactNode;
  /**
   * Card variant
   */
  variant?: 'elevated' | 'outlined' | 'filled';
  /**
   * Optional image source
   */
  imageSrc?: string;
  /**
   * Optional image alt text
   */
  imageAlt?: string;
  /**
   * Optional footer content
   */
  footer?: React.ReactNode;
  /**
   * Optional click handler
   */
  onClick?: () => void;
  /**
   * Optional additional className
   */
  className?: string;
}

export const Card: React.FC<CardProps> = ({
  title,
  children,
  variant = 'elevated',
  imageSrc,
  imageAlt = '',
  footer,
  onClick,
  className = '',
}) => {
  const baseClass = 'sparkline-card';
  const classes = [
    baseClass,
    `${baseClass}--${variant}`,
    onClick ? `${baseClass}--clickable` : '',
    className,
  ].filter(Boolean).join(' ');

  return (
    <div className={classes} onClick={onClick} data-component="card">
      {imageSrc && (
        <div className={`${baseClass}__image`}>
          <img src={imageSrc} alt={imageAlt} />
        </div>
      )}
      <div className={`${baseClass}__content`}>
        {title && <h3 className={`${baseClass}__title`}>{title}</h3>}
        <div className={`${baseClass}__body`}>{children}</div>
      </div>
      {footer && <div className={`${baseClass}__footer`}>{footer}</div>}
    </div>
  );
};

// src/components/Card/Card.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sparkline-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './Card.component.html',
  styleUrls: ['./Card.css'],
})
export class CardComponent {
  @Input() title?: string;
  @Input() variant: 'elevated' | 'outlined' | 'filled' = 'elevated';
  @Input() imageSrc?: string;
  @Input() imageAlt = '';
  @Input() clickable = false;
  @Input() bodyText = '';
  @Output() cardClick = new EventEmitter<void>();

  get classes(): string {
    const base = 'sparkline-card';
    return [
      base,
      `${base}--${this.variant}`,
      this.clickable ? `${base}--clickable` : '',
    ].filter(Boolean).join(' ');
  }

  onClick(): void {
    if (this.clickable) {
      this.cardClick.emit();
    }
  }
}

<div [class]="classes" (click)="onClick()" data-component="card">
  <div *ngIf="imageSrc" class="sparkline-card__image">
    <img [src]="imageSrc" [alt]="imageAlt" />
  </div>
  <div class="sparkline-card__content">
    <h3 *ngIf="title" class="sparkline-card__title">{{ title }}</h3>
    <div class="sparkline-card__body">{{ bodyText }}</div>
  </div>
  <div class="sparkline-card__footer">
    <ng-content select="[footer]"></ng-content>
  </div>
</div>
