// src/components/Checkbox/Checkbox.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, AfterViewInit, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'sparkline-checkbox',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './Checkbox.component.html',
  styleUrls: ['./Checkbox.css'],
})
export class CheckboxComponent implements AfterViewInit, OnChanges {
  @Input() label?: string;
  @Input() checked = false;
  @Input() disabled = false;
  @Input() indeterminate = false;
  @Output() checkedChange = new EventEmitter<boolean>();

  @ViewChild('checkboxInput') checkboxInput!: ElementRef<HTMLInputElement>;

  ngAfterViewInit(): void {
    this.updateIndeterminate();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['indeterminate'] && this.checkboxInput) {
      this.updateIndeterminate();
    }
  }

  private updateIndeterminate(): void {
    if (this.checkboxInput) {
      this.checkboxInput.nativeElement.indeterminate = this.indeterminate;
    }
  }

  onChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.checkedChange.emit(input.checked);
  }
}

<label
  class="sparkline-checkbox"
  [class.sparkline-checkbox--disabled]="disabled"
  data-component="checkbox"
>
  <input
    #checkboxInput
    type="checkbox"
    class="sparkline-checkbox__input"
    [checked]="checked"
    [disabled]="disabled"
    (change)="onChange($event)"
  />
  <span class="sparkline-checkbox__checkmark">
    <svg *ngIf="checked && !indeterminate" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M10 3L4.5 8.5L2 6" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <svg *ngIf="indeterminate" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M2 6H10" stroke="white" stroke-width="2" stroke-linecap="round"/>
    </svg>
  </span>
  <span *ngIf="label" class="sparkline-checkbox__label">{{ label }}</span>
</label>

// src/components/Checkbox/Checkbox.tsx
import React from 'react';
import './Checkbox.css';

export interface CheckboxProps {
  /**
   * Checkbox label
   */
  label?: string;
  /**
   * Checked state
   */
  checked?: boolean;
  /**
   * Disabled state
   */
  disabled?: boolean;
  /**
   * Indeterminate state
   */
  indeterminate?: boolean;
  /**
   * Change handler
   */
  onChange?: (checked: boolean) => void;
  /**
   * Optional additional className
   */
  className?: string;
}

export const Checkbox: React.FC<CheckboxProps> = ({
  label,
  checked = false,
  disabled = false,
  indeterminate = false,
  onChange,
  className = '',
}) => {
  const baseClass = 'sparkline-checkbox';
  const checkboxRef = React.useRef<HTMLInputElement>(null);

  React.useEffect(() => {
    if (checkboxRef.current) {
      checkboxRef.current.indeterminate = indeterminate;
    }
  }, [indeterminate]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (onChange) {
      onChange(e.target.checked);
    }
  };

  return (
    <label className={`${baseClass} ${disabled ? `${baseClass}--disabled` : ''} ${className}`} data-component="checkbox">
      <input
        ref={checkboxRef}
        type="checkbox"
        className={`${baseClass}__input`}
        checked={checked}
        disabled={disabled}
        onChange={handleChange}
      />
      <span className={`${baseClass}__checkmark`}>
        {checked && !indeterminate && (
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M10 3L4.5 8.5L2 6" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        )}
        {indeterminate && (
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M2 6H10" stroke="white" strokeWidth="2" strokeLinecap="round"/>
          </svg>
        )}
      </span>
      {label && <span className={`${baseClass}__label`}>{label}</span>}
    </label>
  );
};
