// src/components/ButtonGroup/ButtonGroup.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

export interface ButtonGroupButton {
  label: string;
  selected?: boolean;
}

@Component({
  selector: 'sparkline-button-group',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './ButtonGroup.component.html',
  styleUrls: ['./ButtonGroup.css'],
})
export class ButtonGroupComponent {
  @Input() buttons: ButtonGroupButton[] = [];
  @Input() size: 'small' | 'large' = 'large';
  @Input() variant: 'primary' | 'secondary' = 'primary';
  @Input() showLeftIcons = false;
  @Input() showRightIcons = false;
  @Input() disabled = false;

  get classes(): string {
    const base = 'sparkline-button-group';
    return [
      base,
      `${base}--${this.size}`,
      `${base}--${this.variant}`,
      this.disabled ? `${base}--disabled` : '',
    ].filter(Boolean).join(' ');
  }
}

<div [class]="classes" data-component="button-group">
  <button
    *ngFor="let button of buttons"
    class="sparkline-button-group__button"
    [class.sparkline-button-group__button--selected]="button.selected"
    [disabled]="disabled"
  >
    <span *ngIf="showLeftIcons" class="sparkline-button-group__icon">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M15 18L9 12L15 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
    <span *ngIf="button.label" class="sparkline-button-group__label">{{ button.label }}</span>
    <span *ngIf="showRightIcons" class="sparkline-button-group__icon">
      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M9 18L15 12L9 6" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
    </span>
  </button>
</div>

// src/components/ButtonGroup/ButtonGroup.tsx
import React from 'react';
import './ButtonGroup.css';

export interface ButtonGroupButton {
  label: string;
  icon?: React.ReactNode;
  onClick?: () => void;
  selected?: boolean;
}

export interface ButtonGroupProps {
  /**
   * Array of buttons to display
   */
  buttons: ButtonGroupButton[];
  /**
   * Button size
   */
  size?: 'small' | 'large';
  /**
   * Visual style variant
   */
  variant?: 'primary' | 'secondary';
  /**
   * Show left icons on buttons
   */
  showLeftIcons?: boolean;
  /**
   * Show right icons on buttons
   */
  showRightIcons?: boolean;
  /**
   * Disabled state for the entire group
   */
  disabled?: boolean;
  /**
   * Optional additional className
   */
  className?: string;
}

const defaultLeftIcon = (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M15 18L9 12L15 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

const defaultRightIcon = (
  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M9 18L15 12L9 6" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
);

export const ButtonGroup: React.FC<ButtonGroupProps> = ({
  buttons,
  size = 'large',
  variant = 'primary',
  showLeftIcons = false,
  showRightIcons = false,
  disabled = false,
  className = '',
}) => {
  const baseClass = 'sparkline-button-group';
  const classes = [
    baseClass,
    `${baseClass}--${size}`,
    `${baseClass}--${variant}`,
    disabled && `${baseClass}--disabled`,
    className,
  ].filter(Boolean).join(' ');

  return (
    <div className={classes} data-component="button-group">
      {buttons.map((button, index) => (
        <button
          key={index}
          className={`${baseClass}__button ${button.selected ? `${baseClass}__button--selected` : ''}`}
          onClick={button.onClick}
          disabled={disabled}
        >
          {showLeftIcons && (
            <span className={`${baseClass}__icon`}>
              {button.icon || defaultLeftIcon}
            </span>
          )}
          {button.label && (
            <span className={`${baseClass}__label`}>{button.label}</span>
          )}
          {showRightIcons && (
            <span className={`${baseClass}__icon`}>
              {defaultRightIcon}
            </span>
          )}
        </button>
      ))}
    </div>
  );
};
